#############################
# Makefile
# Author: Lester
#############################

# cross-compile : set PREFIX and HOST
PREFIX     = 
HOST       = 

# Compiler
CC         = $(HOST)gcc
DEFINES    = -DQSI_ASSERT -D_GNU_SOURCE
CFLAGS     = -g3 -Wall -std=gnu99 $(DEFINES)
INCPATH    = -I$(PREFIX)/usr/include -I$(PREFIX)/usr/local/include -I. -I./include
LINK       = $(HOST)gcc
LIBPATH    = -L$(PREFIX)/usr/lib -L$(PREFIX)/usr/local/lib -L$(PREFIX)/lib
# -Wl,-rpath=dir : Add a directory to the runtime library search path
RPATH      =
# -Wl,-rpath-link : When using ELF, one shared library may require another. It's only effective at link time
RPATH_LINK = $(PREFIX)/usr/lib
LFLAGS     =                                  
LIBS       = $(LIBPATH) -lpthread -lts
AR         = $(HOST)ar


OBJECTS    = ./tm_test.o   \
			 ./fbutils.o   \
			 ./font_8x8.o  \
			 
# All Target
all: tm-test

tm-test: $(OBJECTS)
	@echo 'Building target: $@'
	$(CC) -o $@ $(OBJECTS) $(LFLAGS) $(LIBS)  

$(OBJECTS): %.o: %.c
	$(CC) -c $(CFLAGS) $(INCPATH) $< -o $@
	

	
clean:
	rm -f $(OBJECTS)
	


